import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import Loader from '../components/common/Loader';
import ErrorBanner from '../components/common/ErrorBanner';
import Button from '../components/common/Button';
import DayCard from '../components/itinerary/DayCard';
import TipsList from '../components/itinerary/TipsList';
import Input from '../components/common/Input';
import { getItinerary, getTravelEstimate } from '../api/tripService';

/* ── AI attribution badge ─────────────────────────────────── */
function GeneratedByBadge({ generatedBy }) {
  if (!generatedBy) return null;
  const isGemini = generatedBy === 'gemini';
  return (
    <span className={`
      inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold
      ${isGemini
        ? 'bg-purple-50 text-purple-700 border border-purple-200'
        : 'bg-surface-100 text-surface-600 border border-surface-200'}
    `}>
      <span aria-hidden="true">{isGemini ? '✨' : '📋'}</span>
      {isGemini ? 'AI-generated by Gemini' : 'Template itinerary'}
    </span>
  );
}

/* ── Page ─────────────────────────────────────────────────── */
export default function ItineraryPage() {
  const { tripId } = useParams();

  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState('');
  const [data, setData]           = useState(null);
  const [regenerating, setRegen]  = useState(false);
  
  const [originCity, setOriginCity] = useState('');
  const [estimating, setEstimating] = useState(false);
  const [estimateData, setEstimateData] = useState(null);
  const [estimateError, setEstimateError] = useState('');

  /* ── Travel Estimate ────────────────────────────────────── */
  async function handleEstimate() {
    if (!originCity.trim()) return;
    setEstimating(true);
    setEstimateError('');
    try {
      const result = await getTravelEstimate(tripId, originCity);
      setEstimateData(result);
    } catch (err) {
      setEstimateError(err.message ?? 'Could not calculate distance.');
    } finally {
      setEstimating(false);
    }
  }

  /* ── Fetch itinerary ────────────────────────────────────── */
  async function fetchItinerary(force = false) {
    if (force) setRegen(true); else setLoading(true);
    setError('');
    try {
      const result = await getItinerary(tripId, force);
      setData(result);
    } catch (err) {
      setError(err.message ?? 'Could not load the itinerary.');
    } finally {
      setLoading(false);
      setRegen(false);
    }
  }

  useEffect(() => { fetchItinerary(); }, [tripId]);

  /* ── Derived data ───────────────────────────────────────── */
  const itinerary   = data?.itinerary ?? {};
  const dailyPlan   = itinerary.daily_plan ?? [];
  const weatherData = data?.weather_data  ?? {};

  // Extract sorted date keys so DayCard can match weather by day index
  const dateDates   = Object.keys(weatherData).sort();

  /* ══ RENDER STATES ════════════════════════════════════════ */

  if (loading) {
    return (
      <Loader message="Generating your personalised itinerary… this may take a moment." />
    );
  }

  if (error) {
    return (
      <div className="container-app py-20 max-w-lg text-center animate-fade-in">
        <div className="text-5xl mb-4" aria-hidden="true">😕</div>
        <h1 className="text-2xl font-bold text-surface-900 mb-2">
          Couldn't load itinerary
        </h1>
        <p className="text-surface-500 mb-6">{error}</p>
        <div className="flex gap-3 justify-center flex-wrap">
          <Button onClick={() => fetchItinerary()}>Try Again</Button>
          <Button
            variant="secondary"
            as={Link}
            to={`/trip/${tripId}/results`}
          >
            ← Back to Results
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in">

      {/* ══ HERO BANNER ══════════════════════════════════════ */}
      <div className="bg-gradient-to-br from-brand-900 via-brand-800 to-brand-600 text-white">
        <div className="container-app py-14 sm:py-20">
          <div className="max-w-3xl">
            {/* Breadcrumb */}
            <Link
              to={`/trip/${tripId}/results`}
              className="
                inline-flex items-center gap-1.5 text-xs text-white/60
                hover:text-white/90 transition-colors mb-6
              "
            >
              ← Back to Results
            </Link>

            <p className="text-xs font-bold uppercase tracking-widest text-brand-300 mb-2">
              Your Itinerary
            </p>
            <h1 className="text-4xl sm:text-5xl font-extrabold leading-tight mb-4">
              {data?.destination ?? 'Your Destination'}
            </h1>

            {/* Overview */}
            {itinerary.overview && (
              <p className="text-white/70 text-lg leading-relaxed max-w-2xl mb-6">
                {itinerary.overview}
              </p>
            )}

            {/* Meta row */}
            <div className="flex flex-wrap items-center gap-3">
              <GeneratedByBadge generatedBy={data?.generated_by} />
              {dailyPlan.length > 0 && (
                <span className="text-sm text-white/60">
                  {dailyPlan.length} day{dailyPlan.length !== 1 ? 's' : ''}
                </span>
              )}
              <Button
                variant="secondary"
                size="sm"
                loading={regenerating}
                onClick={() => fetchItinerary(true)}
                className="ml-auto border-white/20 text-white hover:bg-white/10"
              >
                ↻ Regenerate
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* ══ BODY ═════════════════════════════════════════════ */}
      <div className="container-app py-12">
        <ErrorBanner message={error} className="mb-8" />

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-12 items-start">

          {/* ── LEFT: Day-by-day timeline ─────────────────── */}
          <section aria-label="Daily plan">
            <h2 className="text-xl font-bold text-surface-900 mb-8">
              Day-by-Day Plan
            </h2>

            {dailyPlan.length === 0 ? (
              <p className="text-surface-400 py-12 text-center">
                No daily plan available.
              </p>
            ) : (
              /* ── Vertical timeline ── */
              <ol className="relative flex flex-col gap-0" role="list">
                {/* The vertical connector line */}
                <li
                  aria-hidden="true"
                  className="
                    pointer-events-none absolute left-[19px] top-10 bottom-10
                    w-0.5 bg-gradient-to-b from-brand-300 via-brand-200 to-surface-200
                  "
                />

                {dailyPlan.map((day, idx) => (
                  <li key={day.day ?? idx} className="relative flex gap-5 pb-8 last:pb-0">

                    {/* ── Timeline dot ── */}
                    <div className="relative z-10 flex-shrink-0 mt-6">
                      <div className={`
                        flex h-10 w-10 items-center justify-center rounded-full
                        border-2 font-bold text-sm shadow-sm
                        ${idx === 0
                          ? 'border-brand-500 bg-brand-600 text-white'
                          : 'border-surface-300 bg-white text-surface-600'}
                      `}>
                        {day.day ?? idx + 1}
                      </div>
                    </div>

                    {/* ── Day card ── */}
                    <div className="flex-1 min-w-0">
                      <DayCard
                        day={day}
                        weatherData={weatherData}
                        dateDates={dateDates}
                      />
                    </div>

                  </li>
                ))}
              </ol>
            )}
          </section>

          {/* ── RIGHT: Sidebar tips ───────────────────────── */}
          <aside className="flex flex-col gap-8 lg:sticky lg:top-24">

            {/* Packing tips */}
            <div className="rounded-2xl border border-surface-200 bg-white p-6 shadow-sm">
              <TipsList
                title="Packing Tips"
                icon="🎒"
                items={itinerary.packing_tips}
                variant="default"
              />
            </div>

            {/* Local food */}
            <div className="rounded-2xl border border-amber-100 bg-amber-50/50 p-6 shadow-sm">
              <TipsList
                title="Local Food to Try"
                icon="🍜"
                items={itinerary.local_food_to_try}
                variant="food"
              />
            </div>

            {/* Travel tips */}
            {itinerary.travel_tips?.length > 0 && (
              <div className="rounded-2xl border border-brand-100 bg-brand-50/50 p-6 shadow-sm">
                <TipsList
                  title="Travel Tips"
                  icon="💡"
                  items={itinerary.travel_tips}
                  variant="tip"
                />
              </div>
            )}

            {/* Travel Estimate */}
            <div className="rounded-2xl border border-surface-200 bg-white p-6 shadow-sm">
              <h3 className="text-base font-bold text-surface-900 mb-4 flex items-center gap-2">
                <span aria-hidden="true">🗺️</span> Cost Estimator
              </h3>
              <p className="text-xs text-surface-500 mb-4">
                Enter your starting city to see heuristic travel costs to {data?.destination ?? 'the destination'}.
              </p>
              
              <div className="flex flex-col gap-3">
                <Input
                  id="origin-city"
                  placeholder="e.g. Delhi"
                  value={originCity}
                  onChange={(e) => setOriginCity(e.target.value)}
                />
                
                {estimateError && (
                  <p className="text-xs text-red-500 font-medium">{estimateError}</p>
                )}
                
                <Button 
                  onClick={handleEstimate} 
                  loading={estimating}
                  disabled={!originCity.trim()}
                  size="sm"
                >
                  Calculate Cost
                </Button>
              </div>

              {estimateData && (
                <div className="mt-5 space-y-3 pt-4 border-t border-surface-100 animate-fade-in">
                  <p className="text-xs font-semibold text-surface-400 uppercase tracking-wider">
                    Distance: {estimateData.distance_km} km
                  </p>
                  
                  <div className="flex items-center justify-between text-sm">
                    <span className="flex items-center gap-2 font-medium text-surface-700">
                      <span aria-hidden="true">🚂</span> Train
                    </span>
                    <span className="font-semibold text-surface-900">₹{estimateData.costs?.train}</span>
                  </div>
                  
                  <div className="flex items-center justify-between text-sm">
                    <span className="flex items-center gap-2 font-medium text-surface-700">
                      <span aria-hidden="true">🚌</span> Bus
                    </span>
                    <span className="font-semibold text-surface-900">₹{estimateData.costs?.bus}</span>
                  </div>
                  
                  <div className="flex items-center justify-between text-sm">
                    <span className="flex items-center gap-2 font-medium text-surface-700">
                      <span aria-hidden="true">✈️</span> Flight
                    </span>
                    <span className="font-semibold text-surface-900">₹{estimateData.costs?.flight}</span>
                  </div>
                </div>
              )}
            </div>

            {/* Back to results */}
            <Button
              variant="secondary"
              as={Link}
              to={`/trip/${tripId}/results`}
              className="w-full"
            >
              ← Change Destination
            </Button>

          </aside>
        </div>
      </div>

    </div>
  );
}
